### ISSUE TITLE
Wrong multiplier for balance of stock/mutual funds accounts

### ISSUE THREAD

**Issue by jen2014** [holtrop/ruby-gnucash#7]
The balance of a stock account  comes out 100 times too high (the divider in the XML is 10000, not 100).

I attached a gnucash book and test script:
[gct_s.rb 2.zip](https://github.com/holtrop/ruby-gnucash/files/1257479/gct_s.rb.2.zip)
[Test_book.gnucash.zip](https://github.com/holtrop/ruby-gnucash/files/1257490/Test_book.gnucash.zip)

**Comment by holtrop** [comment]
I fixed the Value class to allow mixing Value objects with different divisors and pushed v1.2.2.
